# Structure: outermost layer is survey (e.g., DES, LSST, ROMAN, etc.) Inner layer indicates data file type (e.g., DUMP, SIM, DATA).
# The subscript indicates the SN type (e.g., IA, CC, etc.) ALL indicates a mixture of SN types.

# DES:
#   COMMON_ROOT: "/scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATE_ANALYSIS"

#   DUMP_IA: COMMON_ROOT+'/1_SIM/DESIA_NOMINAL/PIP_D5YR_RATE_BCOR_NOMINAL_DESIA_NOMINAL/PIP_D5YR_RATE_BCOR_NOMINAL_DESIA_NOMINAL.DUMP.gz'
#   SIM_IA: COMMON_ROOT+'/5_MERGE/MERGE_D5_DESIA_NOMINAL/output/PIP_D5YR_RATE_BCOR_NOMINAL_DESIA_NOMINAL/FITOPT000.FITRES.gz'
#   DATA_IA: COMMON_ROOT+'/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_IA-0001/FITOPT000.FITRES.gz'

#   DUMP_CC: COMMON_ROOT+"/1_SIM/DATADES_SIM_CC/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_CC-0001/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_CC-0001.DUMP.gz
#   SIM_CC: COMMON_ROOT+'/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_CC-0001/FITOPT000.FITRES.gz'
#   DATA_CC: COMMON_ROOT+"/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_CC-0001/FITOPT000.FITRES.gz"

#   # This might go away in the future
#   corecollapse_are_separate: true

#DES:
#  DUMP_IA: C:\Users\cmeldorf\Desktop\DESSIMrun\COLE_D5YR_SIM_NOMINAL\1_SIM\DATADESSIM\PIP_COLE_D5YR_SIM_NOMINAL_DATADESSIM-0001\PIP_COLE_D5YR_SIM_NOMINAL_DATADESSIM-0001.DUMP.gz

DES:
  DUMP_IA: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATE_ANALYSIS/1_SIM/DESIA_NOMINAL/PIP_D5YR_RATE_BCOR_NOMINAL_DESIA_NOMINAL/PIP_D5YR_RATE_BCOR_NOMINAL_DESIA_NOMINAL.DUMP.gz
  SIM_IA: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATE_ANALYSIS/5_MERGE/MERGE_D5_DESIA_NOMINAL/output/PIP_D5YR_RATE_BCOR_NOMINAL_DESIA_NOMINAL/FITOPT000.FITRES.gz
  DATA_IA: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATE_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM/output/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_IA-0001/FITOPT000.FITRES.gz

  DUMP_CC: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATE_ANALYSIS/1_SIM/DATADES_SIM_CC/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_CC-0001/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_CC-0001.DUMP.gz
  # change the below to a different sim file
  SIM_CC: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATE_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_CC-0001/FITOPT000.FITRES.gz
  DATA_CC: /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_RATE_ANALYSIS/5_MERGE/MERGE_Dsys_DATADES_SIM_CC/output/PIP_D5YR_RATE_SIM_NOMINAL_DATADESSIM_CC-0001/FITOPT000.FITRES.gz