# Structure: outermost layer is survey (e.g., DES, LSST, ROMAN, etc.) Inner layer indicates data file type (e.g., DUMP, SIM, DATA).
# The subscript indicates the SN type (e.g., IA, CC, etc.) ALL indicates a mixture of SN types.

FIT_OPTIONS:
  RATE_FUNCTION: power_law


ROMAN:
  FIT_OPTIONS:
    RATE_FUNC: power_law
    RATE_PARAMS: 2.27E-5, 1.7
    Z_BINS: 20
    MIN_Z: 0.2
    MAX_Z: 2.0
    CC_ARE_SEPARATE: false

  DUMP_ALL:
    PATH: /scratch/midway2/rkessler/PIPPIN_OUTPUT/CFM_ROTAC_BCOR_RERUN/1_SIM/SUPERNOVA/PIP_CFM_ROTAC_BCOR_RERUN_SUPERNOVA/PIP_CFM_ROTAC_BCOR_RERUN_SUPERNOVA.DUMP.gz
    ZCOL: ZCMB
    SNTYPECOL: SNTYPE
    IA_VALS:
      - 10
  SIM_ALL:
    SNTYPECOL: SNTYPE
    IA_VALS:
      - 10
    PATH: /home/colefmeldorf/sauron/CFM_ROTAC_BCOR_RERUN_new.csv
    ZCOL: REDSHIFT_FINAL
    TRUEZCOL: SIM_REDSHIFT_CMB
  DATA_ALL:
    PATH: /home/colefmeldorf/sauron/CFM_ROTAC_BCOR_RERUN_new.csv
    #PATH: /home/colefmeldorf/sauron/CFM_ROTAC_PZ_new.csv
    ZCOL: REDSHIFT_FINAL



